[tool.pytest.ini_options]
addopts = "-q"
pythonpath = [".", "src/backend"]
filterwarnings = ["ignore::DeprecationWarning"]

# Future tooling examples (uncomment as needed):
# [tool.black]
# line-length = 100
# target-version = ["py312"]
#
# [tool.isort]
# profile = "black"
#
# [tool.coverage.run]
# branch = true
# source = ["src/backend"]
